### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by FabioAntunes** [logzio/logzio-python-handler#65]
Hey folks!

Copying and paste your example:

```
import logging

import logging.config

logging.config.fileConfig('logging.conf')
logger = logging.getLogger('LogzioLogger')

logger.info('Application is running! (Python Handler)')

try:
    1/0
except:
    logger.exception("Don't divide by zero!")

```

logging.conf

```
[handlers]
keys=LogzioHandler

[handler_LogzioHandler]
class=logzio.handler.LogzioHandler
formatter=logzioFormat
args=('my_logzio_token', 'python', 3, 'https://listener.logz.io:8071')

[formatters]
keys=logzioFormat

[loggers]
keys=root

[logger_root]<
handlers=LogzioHandler
level=INFO

[formatter_logzioFormat]
format={"additional_field": "value"}
```

Produces the following error:

```
Traceback (most recent call last):
  File "/Users/user/work/snyk/ops/sequencer/blah.py", line 6, in <module>
    logging.config.fileConfig('logging.conf')
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/config.py", line 119, in _create_formatters
    f = c(fs, dfs, stl)
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 570, in __init__
    self._style.validate()
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 423, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '{"additional_field": "value"}' for '%' style
```

Any guidance or help would be much appreciated

**Comment by mirii1994** [comment]
Hi @FabioAntunes ,
It is recommended to use in Python 3.8+ in the method logging.config.dictConfig().
You can see further explanation in [python's official documentation](https://docs.python.org/3/library/logging.config.html#configuration-file-format).
We updated a while ago the code sample to use dictConfig instead :)
Let me know if after changing it to dictConfig solved this issue for you.
